### PR TITLE
The middleware included in this lib is busted in python3.7

### PR DESCRIPTION
**Pull request by jlward**

### CODE REVIEW

**Comment by jlward** [comment]
```
  py27-django1.11: commands succeeded
  py37-django1.11: commands succeeded
  py37-django2.20: commands succeeded
  congratulations :)
```

**Comment by bocribbz** [comment]
i know its not used, you can probably remove `django18` from tox.ini

**Comment by bocribbz** [comment]
for later reference, some guides on how to make middlewares work with old and new styles django
https://docs.djangoproject.com/en/2.2/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

there seems to be a mixing that does what you did here.

**Comment by bocribbz** [comment]
> there seems to be a mixin that does what you did here.

actually it doesnt do what you did here, but makes some magic to have middlewares work with both old and new style middlewres

**Comment by jlward** [comment]
> there seems to be a mixing that does what you did here.

I followed what the top of the file said to do. But who knows.

**Comment by bocribbz** [comment]
`is busted in python3.7`
is not busted because of python, it's busted more because of django >1.10 :)

> I followed what the top of the file said to do. But who knows.

yup, makes sense, since we dont support django <1.10

**Comment by jlward** [comment]
>  is not busted because of python, it's busted more because of django >1.10 :)

I mean, we are using it in our app. And it doesn't seem to be causing any problems.

The main reason for this issue was thy syntax error we were getting with the `lambda` into `map`. And since the tests here have switched to `MIDDLEWARE` instead of `MIDDLEWARE_CLASSES`, it needed to be updated. I wonder if I'll need to do another PR to fix it to work with `MIDDLEWARE_CLASSES`. Since that's what we are using in PolicyStat. Oh well, we'll find out soon, we have tests going.

**Pull request merged**
